### ISSUE TITLE
Feature Request - Add a setting for how long the notification lasts

### ISSUE THREAD

**Issue by KRSteinke** [aklos/save-notification#1]
I would like the ability to control how long the duration of the notification lasts.

**Comment by aklos** [comment]
Sounds like a good idea, because I know that the notifications can get in the way sometimes.

I guess I'll just add a settable timer for each notification box (save success, save info, no modifications) with toggles.

**Comment by KRSteinke** [comment]
Yeah that should work. I really just like the notification as a quick confirmation that my file did save, since there is a lot of stuff in my dev environment that is kicked off onSave. (Recompiling JS, linting code, then launching the app in browser after every save)

The delay in getting the notification to go away is most noticeable when I'm trying to switch to a Tab that's located underneath the notification (like when I have a lot of tabs open), or if I'm trying to click on something in the Atom-minimap in the current file

**Comment by aklos** [comment]
Added in plugin settings
